//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgAssembly {
            get {
                object obj = ResourceManager.GetObject("ImgAssembly", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgClass {
            get {
                object obj = ResourceManager.GetObject("ImgClass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgDelegate {
            get {
                object obj = ResourceManager.GetObject("ImgDelegate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgEnum {
            get {
                object obj = ResourceManager.GetObject("ImgEnum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgEvent {
            get {
                object obj = ResourceManager.GetObject("ImgEvent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgInterface {
            get {
                object obj = ResourceManager.GetObject("ImgInterface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgMember {
            get {
                object obj = ResourceManager.GetObject("ImgMember", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgPrivateField {
            get {
                object obj = ResourceManager.GetObject("ImgPrivateField", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgPrivateMethod {
            get {
                object obj = ResourceManager.GetObject("ImgPrivateMethod", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgPrivateProperty {
            get {
                object obj = ResourceManager.GetObject("ImgPrivateProperty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgProtectedField {
            get {
                object obj = ResourceManager.GetObject("ImgProtectedField", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgProtectedMethod {
            get {
                object obj = ResourceManager.GetObject("ImgProtectedMethod", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgProtectedProperty {
            get {
                object obj = ResourceManager.GetObject("ImgProtectedProperty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgPublicField {
            get {
                object obj = ResourceManager.GetObject("ImgPublicField", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgPublicMethod {
            get {
                object obj = ResourceManager.GetObject("ImgPublicMethod", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgPublicProperty {
            get {
                object obj = ResourceManager.GetObject("ImgPublicProperty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgStructure {
            get {
                object obj = ResourceManager.GetObject("ImgStructure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ImgType {
            get {
                object obj = ResourceManager.GetObject("ImgType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 程序集 的本地化字符串。
        /// </summary>
        internal static string strAssembly {
            get {
                return ResourceManager.GetString("strAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成器配置文件|*.builder 的本地化字符串。
        /// </summary>
        internal static string strBuilderFilter {
            get {
                return ResourceManager.GetString("strBuilderFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类 的本地化字符串。
        /// </summary>
        internal static string strClass {
            get {
                return ResourceManager.GetString("strClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 构造函数 的本地化字符串。
        /// </summary>
        internal static string strConstructor {
            get {
                return ResourceManager.GetString("strConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 委托 的本地化字符串。
        /// </summary>
        internal static string strDelegate {
            get {
                return ResourceManager.GetString("strDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 枚举 的本地化字符串。
        /// </summary>
        internal static string strEnumeration {
            get {
                return ResourceManager.GetString("strEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string strError {
            get {
                return ResourceManager.GetString("strError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹已存在 的本地化字符串。
        /// </summary>
        internal static string strError1 {
            get {
                return ResourceManager.GetString("strError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称不能为空 的本地化字符串。
        /// </summary>
        internal static string strError2 {
            get {
                return ResourceManager.GetString("strError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成器名称不能为空 的本地化字符串。
        /// </summary>
        internal static string strError3 {
            get {
                return ResourceManager.GetString("strError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解决方案位置不能为空 的本地化字符串。
        /// </summary>
        internal static string strError4 {
            get {
                return ResourceManager.GetString("strError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命名空间不能为空 的本地化字符串。
        /// </summary>
        internal static string strError5 {
            get {
                return ResourceManager.GetString("strError5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件 的本地化字符串。
        /// </summary>
        internal static string strEvent {
            get {
                return ResourceManager.GetString("strEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段 的本地化字符串。
        /// </summary>
        internal static string strField {
            get {
                return ResourceManager.GetString("strField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成自定义文档生成器工程——扩展XML注释标志 的本地化字符串。
        /// </summary>
        internal static string strGSOText1 {
            get {
                return ResourceManager.GetString("strGSOText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成自定义文档生成器工程——自定义页面 的本地化字符串。
        /// </summary>
        internal static string strGSOText2 {
            get {
                return ResourceManager.GetString("strGSOText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成自定义文档生成器工程 的本地化字符串。
        /// </summary>
        internal static string strGSOText3 {
            get {
                return ResourceManager.GetString("strGSOText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成自定义文档生成器工程——扩展页面中显示的节 的本地化字符串。
        /// </summary>
        internal static string strGSOText4 {
            get {
                return ResourceManager.GetString("strGSOText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序集(*.dll,*.exe)|*.dll;*.exe 的本地化字符串。
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML文件(*.xml)|*.xml 的本地化字符串。
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除程序集 的本地化字符串。
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有程序集 的本地化字符串。
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有类型 的本地化字符串。
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速选择 的本地化字符串。
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成类型 的本地化字符串。
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成文档 的本地化字符串。
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速选择 的本地化字符串。
        /// </summary>
        internal static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启后生效！ 的本地化字符串。
        /// </summary>
        internal static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入标题！ 的本地化字符串。
        /// </summary>
        internal static string String51 {
            get {
                return ResourceManager.GetString("String51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序集已添加！ 的本地化字符串。
        /// </summary>
        internal static string String52 {
            get {
                return ResourceManager.GetString("String52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML文件已添加！ 的本地化字符串。
        /// </summary>
        internal static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继承的成员 的本地化字符串。
        /// </summary>
        internal static string strInheritMember {
            get {
                return ResourceManager.GetString("strInheritMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接口 的本地化字符串。
        /// </summary>
        internal static string strInterface {
            get {
                return ResourceManager.GetString("strInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成员 的本地化字符串。
        /// </summary>
        internal static string strMember {
            get {
                return ResourceManager.GetString("strMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方法 的本地化字符串。
        /// </summary>
        internal static string strMethod {
            get {
                return ResourceManager.GetString("strMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命名空间 的本地化字符串。
        /// </summary>
        internal static string strNamespace {
            get {
                return ResourceManager.GetString("strNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非公共类型 的本地化字符串。
        /// </summary>
        internal static string strNonPublicType {
            get {
                return ResourceManager.GetString("strNonPublicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 私有字段 的本地化字符串。
        /// </summary>
        internal static string strPrivateField {
            get {
                return ResourceManager.GetString("strPrivateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 私有方法 的本地化字符串。
        /// </summary>
        internal static string strPrivateMethod {
            get {
                return ResourceManager.GetString("strPrivateMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 私有属性 的本地化字符串。
        /// </summary>
        internal static string strPrivateProperty {
            get {
                return ResourceManager.GetString("strPrivateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        internal static string strProperty {
            get {
                return ResourceManager.GetString("strProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 受保护字段 的本地化字符串。
        /// </summary>
        internal static string strProtectedField {
            get {
                return ResourceManager.GetString("strProtectedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 受保护方法 的本地化字符串。
        /// </summary>
        internal static string strProtectedMethod {
            get {
                return ResourceManager.GetString("strProtectedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 受保护属性 的本地化字符串。
        /// </summary>
        internal static string strProtectedProperty {
            get {
                return ResourceManager.GetString("strProtectedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公共字段 的本地化字符串。
        /// </summary>
        internal static string strPublicField {
            get {
                return ResourceManager.GetString("strPublicField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公共方法 的本地化字符串。
        /// </summary>
        internal static string strPublicMethod {
            get {
                return ResourceManager.GetString("strPublicMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公共属性 的本地化字符串。
        /// </summary>
        internal static string strPublicProperty {
            get {
                return ResourceManager.GetString("strPublicProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公共类型 的本地化字符串。
        /// </summary>
        internal static string strPublicType {
            get {
                return ResourceManager.GetString("strPublicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结构 的本地化字符串。
        /// </summary>
        internal static string strStructure {
            get {
                return ResourceManager.GetString("strStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string strTip {
            get {
                return ResourceManager.GetString("strTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有在{0}所在的文件夹中检测到对应的XML文档文件{1}！
        ///请在工程的项目属性-&gt;生成中,勾选XML文档文件。
        ///如果您将XML文档文件放置在其它文件夹中，请手动添加XML文档文件。 的本地化字符串。
        /// </summary>
        internal static string strTip_NoXML {
            get {
                return ResourceManager.GetString("strTip_NoXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以下生成器由于版本不兼容未能加载: 的本地化字符串。
        /// </summary>
        internal static string strTip3 {
            get {
                return ResourceManager.GetString("strTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档生成器和ADB的版本不兼容！ 的本地化字符串。
        /// </summary>
        internal static string strTip4 {
            get {
                return ResourceManager.GetString("strTip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工程已成功生成 的本地化字符串。
        /// </summary>
        internal static string strTip5 {
            get {
                return ResourceManager.GetString("strTip5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工程已生成失败:{0} 的本地化字符串。
        /// </summary>
        internal static string strTip6 {
            get {
                return ResourceManager.GetString("strTip6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择解决方案位置 的本地化字符串。
        /// </summary>
        internal static string strTip7 {
            get {
                return ResourceManager.GetString("strTip7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        internal static string strType {
            get {
                return ResourceManager.GetString("strType", resourceCulture);
            }
        }
    }
}
