//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB.Factories {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADB.Factories.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=gb2312&quot; /&gt;
        ///    &lt;title&gt;{0}&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    p
        ///    {
        ///    text-indent: 2pc;
        ///    font-family: &apos;Times New Roman&apos;;
        ///    }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div&gt;
        ///        &lt;p&gt;
        ///            .NET�ĵ��������Ѿ�Ϊ������CHM�ĵ����ĵ�������ҳ�漰���CHM�ĵ���Ҫ��HH [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string EditIndex {
            get {
                return ResourceManager.GetString("EditIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似         &lt;p &gt;&lt;a href=&quot;{HREF}&quot; target=&quot;_blank&quot;&gt;{Name}&lt;/a&gt;&lt;/p&gt; 的本地化字符串。
        /// </summary>
        internal static string EditIndex_NS {
            get {
                return ResourceManager.GetString("EditIndex_NS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;HTML&gt;&lt;HEAD&gt;&lt;/HEAD&gt;&lt;BODY&gt;
        ///&lt;OBJECT type=&quot;text/site properties&quot;&gt;&lt;param name=&quot;Window Styles&quot; value=&quot;0x227&quot;&gt;&lt;/OBJECT&gt;
        ///&lt;UL&gt;{目录项}
        ///&lt;/UL&gt;
        ///&lt;/BODY&gt;&lt;/HTML&gt;
        /// 的本地化字符串。
        /// </summary>
        internal static string HHC {
            get {
                return ResourceManager.GetString("HHC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [OPTIONS]
        ///Compatibility=1.1 Or later
        ///Compiled file={CHM文件}
        ///Default window=Main
        ///Default topic={默认}
        ///Contents file={HHC}
        ///Display compile progress=Yes
        ///Full-text search=Yes
        ///
        ///[WINDOWS]
        ///Main=&quot;{标题}&quot;,&quot;{HHC}&quot;,,&quot;{默认}&quot;,&quot;{主页}&quot;,,,,,0x420,0xB4,0x10304E,[80,60,720,540],0x0,0x0,,,,,0
        ///
        ///[FILES]{Files} 的本地化字符串。
        /// </summary>
        internal static string HHP {
            get {
                return ResourceManager.GetString("HHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [OPTIONS]
        ///Compatibility=1.1 Or later
        ///Compiled file={CHM文件}
        ///Default window=Main
        ///Default font=宋体,9,1
        ///Contents file={HHC}
        ///Display compile progress=Yes
        ///Full-text search=Yes
        ///Language=0X804 中文(中国)
        ///
        ///[WINDOWS]
        ///Main=&quot;{标题}&quot;,&quot;{HHC}&quot;,,,,,,,,0x420,0xB4,0x10300E,[80,60,720,540],0x0,0x0,,,,,0
        ///
        ///[FILES]{Files} 的本地化字符串。
        /// </summary>
        internal static string HHP_NoIndex {
            get {
                return ResourceManager.GetString("HHP_NoIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;LI&gt;&lt;OBJECT TYPE=&quot;text/sitemap&quot;&gt;
        ///&lt;PARAM NAME=&quot;Name&quot; VALUE=&quot;{名称}&quot;&gt;
        ///&lt;PARAM NAME=&quot;ImageNumber&quot; value=&quot;{图标}&quot;&gt;
        ///&lt;/OBJECT&gt; 的本地化字符串。
        /// </summary>
        internal static string LI {
            get {
                return ResourceManager.GetString("LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///&lt;LI&gt;&lt;OBJECT TYPE=&quot;text/sitemap&quot;&gt;
        ///&lt;PARAM NAME=&quot;Name&quot; VALUE=&quot;{名称}&quot;&gt;
        ///&lt;PARAM NAME=&quot;Local&quot; VALUE=&quot;{HTML文件}&quot;&gt;
        ///&lt;PARAM NAME=&quot;ImageNumber&quot; value=&quot;{图标}&quot;&gt;
        ///&lt;/OBJECT&gt; 的本地化字符串。
        /// </summary>
        internal static string LI_Link {
            get {
                return ResourceManager.GetString("LI_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;table&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;th&gt;{0}&lt;/th&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;&lt;pre&gt;{1}&lt;/pre&gt;&lt;/td&gt;
        ///        &lt;/tr&gt;
        ///    &lt;/tbody&gt;
        ///&lt;/table&gt;
        /// 的本地化字符串。
        /// </summary>
        internal static string Temp_Declaration {
            get {
                return ResourceManager.GetString("Temp_Declaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;div class=&quot;code&quot;&gt;
        ///    &lt;span&gt;
        ///        &lt;table width=&quot;100%&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///            &lt;tr&gt;
        ///                &lt;th&gt;
        ///                    {Language}
        ///                &lt;/th&gt;
        ///                &lt;th&gt;
        ///                &lt;/th&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///                &lt;td colspan=&quot;2&quot;&gt;
        ///                    &lt;pre&gt;{Code}&lt;/pre&gt;
        ///                &lt;/td&gt;
        ///            &lt;/tr&gt;
        ///        &lt;/table&gt;
        ///    &lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br/&gt;
        /// 的本地化字符串。
        /// </summary>
        internal static string Temp_Example_Code {
            get {
                return ResourceManager.GetString("Temp_Example_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;p&gt;{Example}&lt;/p&gt;
        /// 的本地化字符串。
        /// </summary>
        internal static string Temp_Example_Description {
            get {
                return ResourceManager.GetString("Temp_Example_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;table cellspacing=&quot;2&quot; cellpadding=&quot;5&quot; width=&quot;100%&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;th align=&quot;left&quot;&gt;
        ///                异常类型&lt;/th&gt;
        ///            &lt;th align=&quot;left&quot;&gt;
        ///                条件&lt;/th&gt;
        ///        &lt;/tr&gt;
        ///        {AllRows}
        ///    &lt;/tbody&gt;
        ///&lt;/table&gt;
        /// 的本地化字符串。
        /// </summary>
        internal static string Temp_ExceptionTable {
            get {
                return ResourceManager.GetString("Temp_ExceptionTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;tr valign=&quot;top&quot;&gt;
        ///    &lt;td&gt;
        ///        {Col1}
        ///    &lt;/td&gt;
        ///    &lt;td&gt;
        ///        {Col2}
        ///    &lt;/td&gt;
        ///&lt;/tr&gt; 的本地化字符串。
        /// </summary>
        internal static string Temp_ExceptionTable_Row {
            get {
                return ResourceManager.GetString("Temp_ExceptionTable_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;img alt=&quot;{文本}&quot; src=&quot;files\{图片}&quot;&gt;&lt;/img&gt; 的本地化字符串。
        /// </summary>
        internal static string Temp_Img {
            get {
                return ResourceManager.GetString("Temp_Img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html dir=&quot;ltr&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:ddue=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;
        ///    xmlns:mshelp=&quot;http://msdn.microsoft.com/mshelp&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;{Title}&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset={Encoding}&quot; &gt;
        ///    &lt;meta content=&quot;history&quot; name=&quot;save&quot;&gt;
        ///   
        ///    &lt;link href=&quot;files/Classic.css&quot;
        ///        type=&quot;text/css&quot; rel=&quot;stylesheet&quot;/&gt;
        ///    &lt;link href=&quot;files/HxLink [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Temp_Page {
            get {
                return ResourceManager.GetString("Temp_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;span class=&quot;parameter&quot;&gt;&lt;b&gt;{0}&lt;/b&gt;&lt;/span&gt;
        ///&lt;p&gt;{1}&lt;/p&gt;
        ///&lt;br /&gt; 的本地化字符串。
        /// </summary>
        internal static string Temp_Param {
            get {
                return ResourceManager.GetString("Temp_Param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;h4 class=&quot;subHeading&quot;&gt;{0}&lt;/h4&gt;
        ///&lt;br/&gt;
        ///&lt;pre&gt;{1}&lt;/pre&gt; 的本地化字符串。
        /// </summary>
        internal static string Temp_ParamsBlock {
            get {
                return ResourceManager.GetString("Temp_ParamsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;p&gt;{0}&lt;/p&gt; 的本地化字符串。
        /// </summary>
        internal static string Temp_Remarks {
            get {
                return ResourceManager.GetString("Temp_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;a name=&quot;{ID}&quot;&gt;&lt;/a&gt;
        ///&lt;h1 class=&quot;heading&quot;&gt;
        ///    &lt;span onkeypress=&quot;ExpandCollapse_CheckKey({ID}Toggle)&quot; style=&quot;cursor: default&quot; onclick=&quot;ExpandCollapse({ID}Toggle)&quot;
        ///        tabindex=&quot;0&quot;&gt;
        ///        &lt;img class=&quot;toggle&quot; id=&quot;{ID}Toggle&quot; alt=&quot;Expand&quot; src=&quot;files\Expand.gif&quot; onload=&quot;OnLoadImage()&quot;
        ///            name=&quot;toggleSwitch&quot;&gt;&lt;/img&gt;{Title}&lt;/span&gt;&lt;/h1&gt;
        ///&lt;div class=&quot;section&quot; id=&quot;{ID}Section&quot; style=&quot;display: none&quot; name=&quot;collapseableSection&quot;&gt;
        ///    {Content}
        ///&lt;/div&gt;
        /// 的本地化字符串。
        /// </summary>
        internal static string Temp_Section {
            get {
                return ResourceManager.GetString("Temp_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;table class=&quot;memberListTable&quot; cellspacing=&quot;2&quot; cellpadding=&quot;5&quot; width=&quot;100%&quot;&gt;
        ///    &lt;colgroup&gt;
        ///        &lt;col width=&quot;2%&quot;&gt;
        ///        &lt;col width=&quot;38%&quot;&gt;
        ///        &lt;col width=&quot;60%&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;th&gt;
        ///                    &amp;nbsp;&lt;/th&gt;
        ///                &lt;th style=&quot;border-right-style: none&quot; align=&quot;left&quot;&gt;
        ///                    {Column1}&lt;/th&gt;
        ///                &lt;th style=&quot;border-left-style: none&quot; align=&quot;left&quot;&gt;
        ///                    {Desc}&lt;/th&gt;
        ///            &lt;/tr&gt;
        ///            {AllRows}
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Temp_TypeTable {
            get {
                return ResourceManager.GetString("Temp_TypeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;table class=&quot;memberListTable&quot; cellspacing=&quot;2&quot; cellpadding=&quot;5&quot; width=&quot;100%&quot;&gt;
        ///    &lt;colgroup&gt;
        ///        &lt;col width=&quot;2%&quot;&gt;
        ///        &lt;col width=&quot;38%&quot;&gt;
        ///        &lt;col width=&quot;60%&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;th&gt;
        ///                    &amp;nbsp;&lt;/th&gt;
        ///                &lt;th style=&quot;border-right-style: none&quot; align=&quot;left&quot;&gt;
        ///                    {Column1}&lt;/th&gt;
        ///                &lt;th style=&quot;border-left-style: none&quot; align=&quot;left&quot;&gt;
        ///                    Description&lt;/th&gt;
        ///            &lt;/tr&gt;
        ///            {AllRows [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Temp_TypeTable_en_US {
            get {
                return ResourceManager.GetString("Temp_TypeTable_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;tr valign=&quot;top&quot;&gt;
        ///    &lt;td&gt;{0}&lt;/td&gt;
        ///    &lt;td&gt;&lt;a href=&quot;{1}&quot;&gt;{2}&lt;/a&gt;&lt;/td&gt;
        ///    &lt;td&gt;{3}&lt;/td&gt;
        ///&lt;/tr&gt;  的本地化字符串。
        /// </summary>
        internal static string Temp_TypeTable_Row {
            get {
                return ResourceManager.GetString("Temp_TypeTable_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;UL&gt;
        ///{LI}
        ///&lt;/UL&gt; 的本地化字符串。
        /// </summary>
        internal static string UL {
            get {
                return ResourceManager.GetString("UL", resourceCulture);
            }
        }
    }
}
