//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB.Factories.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADB.Factories.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 E_ 的本地化字符串。
        /// </summary>
        internal static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .html 的本地化字符串。
        /// </summary>
        internal static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 F_ 的本地化字符串。
        /// </summary>
        internal static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M_ 的本地化字符串。
        /// </summary>
        internal static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P_ 的本地化字符串。
        /// </summary>
        internal static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改文档.html 的本地化字符串。
        /// </summary>
        internal static string strAlterDoc {
            get {
                return ResourceManager.GetString("strAlterDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成已取消！ 的本地化字符串。
        /// </summary>
        internal static string strCanceled {
            get {
                return ResourceManager.GetString("strCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类 的本地化字符串。
        /// </summary>
        internal static string strClass {
            get {
                return ResourceManager.GetString("strClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部折叠 的本地化字符串。
        /// </summary>
        internal static string strCollapseAll {
            get {
                return ResourceManager.GetString("strCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 构造函数 的本地化字符串。
        /// </summary>
        internal static string strConstructor {
            get {
                return ResourceManager.GetString("strConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CHM文档(默认) 的本地化字符串。
        /// </summary>
        internal static string strDefault {
            get {
                return ResourceManager.GetString("strDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 委托 的本地化字符串。
        /// </summary>
        internal static string strDelegate {
            get {
                return ResourceManager.GetString("strDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明 的本地化字符串。
        /// </summary>
        internal static string strDesc {
            get {
                return ResourceManager.GetString("strDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 枚举 的本地化字符串。
        /// </summary>
        internal static string strEnumeration {
            get {
                return ResourceManager.GetString("strEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string strError {
            get {
                return ResourceManager.GetString("strError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件 的本地化字符串。
        /// </summary>
        internal static string strEvent {
            get {
                return ResourceManager.GetString("strEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部展开 的本地化字符串。
        /// </summary>
        internal static string strExpandAll {
            get {
                return ResourceManager.GetString("strExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段 的本地化字符串。
        /// </summary>
        internal static string strField {
            get {
                return ResourceManager.GetString("strField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有生成CHM文件，HTML页面文件和CHM工程文件已保存到
        ///{0}中！ 的本地化字符串。
        /// </summary>
        internal static string strHTMLOnly {
            get {
                return ResourceManager.GetString("strHTMLOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index 的本地化字符串。
        /// </summary>
        internal static string strIndex {
            get {
                return ResourceManager.GetString("strIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Templates 的本地化字符串。
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公共类型 的本地化字符串。
        /// </summary>
        internal static string String01 {
            get {
                return ResourceManager.GetString("String01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非公共类型 的本地化字符串。
        /// </summary>
        internal static string String02 {
            get {
                return ResourceManager.GetString("String02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        internal static string String03 {
            get {
                return ResourceManager.GetString("String03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继承的成员 的本地化字符串。
        /// </summary>
        internal static string String04 {
            get {
                return ResourceManager.GetString("String04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成员 的本地化字符串。
        /// </summary>
        internal static string String05 {
            get {
                return ResourceManager.GetString("String05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另一个Build操作正在进行 的本地化字符串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序集 的本地化字符串。
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序集(*.dll,*.exe)|*.dll;*.exe 的本地化字符串。
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML文件(*.xml)|*.xml 的本地化字符串。
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除程序集 的本地化字符串。
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有程序集 的本地化字符串。
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有类型 的本地化字符串。
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档生成 的本地化字符串。
        /// </summary>
        internal static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速选择 的本地化字符串。
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成类型 的本地化字符串。
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        internal static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序集 的本地化字符串。
        /// </summary>
        internal static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML文档 的本地化字符串。
        /// </summary>
        internal static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成文档 的本地化字符串。
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速选择 的本地化字符串。
        /// </summary>
        internal static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 示例 的本地化字符串。
        /// </summary>
        internal static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语法 的本地化字符串。
        /// </summary>
        internal static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        internal static string String45 {
            get {
                return ResourceManager.GetString("String45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        internal static string String46 {
            get {
                return ResourceManager.GetString("String46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回值 的本地化字符串。
        /// </summary>
        internal static string String47 {
            get {
                return ResourceManager.GetString("String47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性值 的本地化字符串。
        /// </summary>
        internal static string String48 {
            get {
                return ResourceManager.GetString("String48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启后生效！ 的本地化字符串。
        /// </summary>
        internal static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否打开文件？ 的本地化字符串。
        /// </summary>
        internal static string String50 {
            get {
                return ResourceManager.GetString("String50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入标题？ 的本地化字符串。
        /// </summary>
        internal static string String51 {
            get {
                return ResourceManager.GetString("String51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序集已添加！ 的本地化字符串。
        /// </summary>
        internal static string String52 {
            get {
                return ResourceManager.GetString("String52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML文件已添加！ 的本地化字符串。
        /// </summary>
        internal static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要取消？ 的本地化字符串。
        /// </summary>
        internal static string String55 {
            get {
                return ResourceManager.GetString("String55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (从{0}继承) 的本地化字符串。
        /// </summary>
        internal static string String56 {
            get {
                return ResourceManager.GetString("String56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接口 的本地化字符串。
        /// </summary>
        internal static string strInterface {
            get {
                return ResourceManager.GetString("strInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方法 的本地化字符串。
        /// </summary>
        internal static string strMethod {
            get {
                return ResourceManager.GetString("strMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命名空间 的本地化字符串。
        /// </summary>
        internal static string strNamespace {
            get {
                return ResourceManager.GetString("strNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不编译CHM文件 的本地化字符串。
        /// </summary>
        internal static string strNoCHM {
            get {
                return ResourceManager.GetString("strNoCHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        internal static string strPic {
            get {
                return ResourceManager.GetString("strPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 私有字段 的本地化字符串。
        /// </summary>
        internal static string strPrivateField {
            get {
                return ResourceManager.GetString("strPrivateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 私有方法 的本地化字符串。
        /// </summary>
        internal static string strPrivateMethod {
            get {
                return ResourceManager.GetString("strPrivateMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 私有属性 的本地化字符串。
        /// </summary>
        internal static string strPrivateProperty {
            get {
                return ResourceManager.GetString("strPrivateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        internal static string strProperty {
            get {
                return ResourceManager.GetString("strProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 受保护字段 的本地化字符串。
        /// </summary>
        internal static string strProtectedField {
            get {
                return ResourceManager.GetString("strProtectedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 受保护方法 的本地化字符串。
        /// </summary>
        internal static string strProtectedMethod {
            get {
                return ResourceManager.GetString("strProtectedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 受保护属性 的本地化字符串。
        /// </summary>
        internal static string strProtectedProperty {
            get {
                return ResourceManager.GetString("strProtectedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公共字段 的本地化字符串。
        /// </summary>
        internal static string strPublicField {
            get {
                return ResourceManager.GetString("strPublicField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公共方法 的本地化字符串。
        /// </summary>
        internal static string strPublicMethod {
            get {
                return ResourceManager.GetString("strPublicMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公共属性 的本地化字符串。
        /// </summary>
        internal static string strPublicProperty {
            get {
                return ResourceManager.GetString("strPublicProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结构 的本地化字符串。
        /// </summary>
        internal static string strStructure {
            get {
                return ResourceManager.GetString("strStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string strTip {
            get {
                return ResourceManager.GetString("strTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入路径！ 的本地化字符串。
        /// </summary>
        internal static string strTip1 {
            get {
                return ResourceManager.GetString("strTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 T_ 的本地化字符串。
        /// </summary>
        internal static string T {
            get {
                return ResourceManager.GetString("T", resourceCulture);
            }
        }
    }
}
